Search component
GingerBoy14/simple-TODO pull request #18
Opened 2020-12-02 16:40 UTC by olenashevchuk

2020-12-02 22:26 UTC, GingerBoy14 requested changes

2020-12-02 22:26 UTC, GingerBoy14 commented on src/components/index.js
> +  return <Search />
You don`t need to use it now in App, because if I merge your pull-request that's create merge-conflict in another pull-request.

2020-12-02 22:26 UTC, GingerBoy14 commented on src/components/Search/Search.js
> +import { useStoreContext } from '../../context'
need to configure jsconfig.json

2020-12-02 22:26 UTC, GingerBoy14 commented on src/components/Search/Search.js
> +import 'antd/dist/antd.css'
should be imported in main app file

2020-12-03 09:22 UTC, sashka2131 approved these changes

2020-12-03 10:21 UTC, GingerBoy14 requested changes

2020-12-03 10:21 UTC, GingerBoy14 commented on src/components/Search/Search.js
> +    />
fixed width - bad practice

2020-12-03 10:21 UTC, GingerBoy14 commented on src/components/index.js
> +
Sasha added it to main index

2020-12-03 19:51 UTC, GingerBoy14 approved these changes

2020-12-03 19:51 UTC, merged